### ISSUE TITLE
提供xctest[swift3]对webdriver服务端的封装

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#377]
## XCTestWD 实现要求

- [x] 遵循现有[wd router](https://github.com/macacajs/webdriver-server/blob/master/lib/server/router.js) 
- [x] 实现xpath等方式的选择器，xpath，name, class name, id
- [x] [手势实现](https://github.com/alibaba/macaca/issues/366)
- [x] 支持多个模拟器启动，[ios 并行实践](https://github.com/alibaba/macaca/issues/212)
- [x] 提供monkey实践(Macaca上层，便于跨平台)
- [x] 提供自动化遍历实践(Macaca上层，便于跨平台)
- [x] 工程中提供sample运行示例

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/212

**Comment by xudafeng** [comment]
- [ ] 键盘收起扩展协议

https://github.com/alibaba/macaca/issues/367

**Comment by SamuelZhaoY** [comment]
4 月底 ， 5 月初目标 完成router,  xpath 实现

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/457 需要考虑并行问题

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/455

**Comment by xudafeng** [comment]
UIAPickerWheel 映射不到 https://github.com/alibaba/macaca/issues/415

**Comment by xudafeng** [comment]
怀疑有内存泄露 https://github.com/alibaba/macaca/issues/406

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/384

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/378 合并到这个issue

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/340

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/263

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/76#issuecomment-297678278

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/493

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/issues
